# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_owner',
            field=models.ManyToManyField(related_name='books', to='student_post.Student'),
        ),
    ]
