# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 02:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_post', '0003_auto_20170629_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assign_to_lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
